apiVersion: apps/v1
kind: Deployment
metadata:
  name: package-registry-build
  namespace: zarf
  labels:
    app: package-registry-build
spec:
  selector:
    matchLabels:
      app: package-registry-build
  template:
    metadata:
      labels:
        app: package-registry-build
    spec:
      containers:
        - name: build-container
          image: "###ZARF_CONST_PUBLISHER_IMAGE###"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          args: ["./build.sh"]
          volumeMounts:
            - name: tls-certs
              mountPath: /usr/local/share/ca-certificates
      volumes:
        - name: tls-certs
          secret:
            secretName: agent-redirector-tls
            items:
              - key: tls.crt
                path: tls.crt
