apiVersion: v1
kind: ConfigMap
metadata:
  name: uploader-scripts
  namespace: zarf
data:
{{ (.Files.Glob "scripts/build.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "scripts/upload.sh").AsConfig | indent 2 }}
