name: images
description: "Create package uploader image"

runs:
  using: composite
  steps:
    - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ghcr.io
        username: dummy
        password: ${{ github.token }}

    - name: Build and push
      uses: docker/build-push-action@35e7dd592106dcd929ef8706706f6d54678d1f67 # v5.3.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/defenseunicorns/zarf-package/dev-dependencies:$GITHUB_SHA
