name: images
description: "Create package uploader image"

runs:
  using: composite
  steps:
    - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ghcr.io
        username: dummy
        password: ${{ github.token }}

    - run: |
        docker buildx build --push --platform linux/amd64 --tag ghcr.io/defenseunicorns/zarf-package/dev-dependencies:$GITHUB_SHA .
      shell: bash
