apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  ZarfRedirector.server: |
    dev.local:53 {
      log
      errors
      rewrite name github.com.dev.local agent-redirector.zarf.svc.cluster.local
      rewrite name pypi.org.dev.local agent-redirector.zarf.svc.cluster.local
      rewrite name registry.npmjs.org.dev.local agent-redirector.zarf.svc.cluster.local
      rewrite name dl.k8s.io.dev.local agent-redirector.zarf.svc.cluster.local
  
      kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
      }
    }
