apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-redirector
  namespace: zarf
  labels:
    app: agent-redirector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent-redirector
  template:
    metadata:
      labels:
        app: agent-redirector
    spec:
      imagePullSecrets:
        - name: private-registry
      containers:
        - name: server
          image: "###ZARF_CONST_AGENT_IMAGE###"
          args: ["/zarf", "internal", "http-proxy", "-l=trace"]
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
          ports:
            - containerPort: 8443
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/certs
              readOnly: true
            - name: zarf-state
              mountPath: /etc/zarf-state
              readOnly: true
            - name: zarf-npm
              mountPath: /etc/zarf-npm
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: agent-redirector-tls
        - name: zarf-state
          secret:
            secretName: zarf-state
        - name: zarf-npm
          secret:
            secretName: agent-redirector-npm
            items:
              - key: npm-token
                path: npm
