apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-redirector-npm-acct
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-redirector-npm-acct-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agent-redirector-npm-acct-role
subjects:
  - kind: ServiceAccount
    name: agent-redirector-npm-acct
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent-redirector-npm-acct-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
