name: Build Images

on:
  push:
    branches: ["main"]

# Abort prior jobs in the same workflow / PR
concurrency:
  group: build-images-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build images
        uses: ./.github/actions/images
